import { Routes } from '@angular/router';
import { RegistroComponent } from './components/actor/registro/registro.component';
import { LoginComponent } from './components/actor/login/login.component';
import { PerfilComponent } from './components/actor/perfil/perfil.component';
import { EditarPerfilComponent } from './components/actor/editar-perfil/editar-perfil.component';
import { ListarProductosComponent } from './components/producto/listar-productos/listar-productos.component';
import { DetallesProductoComponent } from './components/producto/detalles-producto/detalles-producto.component';
import { CarritoComponent } from './components/carrito/carrito.component';
import { SobreNosotrosComponent } from './components/extra/sobre-nosotros/sobre-nosotros.component';
import { PoliticaComponent } from './components/extra/politica/politica.component';
import { TerminosComponent } from './components/extra/terminos/terminos.component';
import { FaqComponent } from './components/extra/faq/faq.component';
import { NotfoundComponent } from './components/notfound/notfound.component';
import { HomeComponent } from './components/home/home.component';
import { ProductosAdminComponent } from './components/producto/productos-admin/productos-admin.component';
import { FormProductoComponent } from './components/producto/form-producto/form-producto.component';
import { ListarPedidosComponent } from './components/actor/listar-pedidos/listar-pedidos.component';

export const routes: Routes = [
    { path: 'login', component: LoginComponent },
    { path: 'registro', component: RegistroComponent },
    { path: 'registro/admin', component: RegistroComponent },
    { path: 'perfil', component: PerfilComponent },
    { path: 'perfil/editar', component: EditarPerfilComponent },
    { path: 'carrito', component: CarritoComponent },
    { path: 'mispedidos', component: ListarPedidosComponent },
    { path: 'productosadmin', component: ProductosAdminComponent },
    { path: 'productos/crear', component: FormProductoComponent },
    { path: 'productos/:id/editar', component: FormProductoComponent },
    { path: 'productos/:id', component: DetallesProductoComponent },
    { path: 'sobrenosotros', component: SobreNosotrosComponent },
    { path: 'politica', component: PoliticaComponent },
    { path: 'terminos', component: TerminosComponent },
    { path: 'faq', component: FaqComponent },
    { path: ':nombreCategoria', component: ListarProductosComponent },
    { path: '', component: HomeComponent },
    { path: '**', component: NotfoundComponent }
];
